sudo: false
dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - make

install:
  - PYVERSION=$TRAVIS_PYTHON_VERSION make devel

script:
  - PYVERSION=$TRAVIS_PYTHON_VERSION COV_FMT=xml make test

after_success:
  - codecov
