sudo: false
dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - make

install:
  - make ci-install

script:
  - make ci-test

after_success:
  - codecov
