language: python
python:
    - "3.4"

os:
    - linux

before_install:
    - pip install --upgrade pip pytest flake8 pylint coverage codecov tox
    - sudo apt-get install python-pygame

after_success:
    - coverage combine
    - coverage report
    - coverage xml
    - codecov

script:
    - tox
