sudo: false
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  # - "3.8"  pygame failed to install

addons:
  apt:
    packages:
      - curl
      - make

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"

install:
  - pip install --upgrade pip
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py > get-poetry.py
  - python get-poetry.py -y
  - source $HOME/.poetry/env
  - poetry install

script:
  - poetry run pytest --cov=./xoinvader --cov-report=xml -s -v xoinvader/tests

after_success:
  - codecov
