sudo: required
language: python
python:
  - "3.4"

os:
  - linux

addons:
  apt:
    packages:
      - python-pygame
      - mercurial

before_install:
  - sudo apt-get build-dep -y python-pygame
  - pip install hg+http://bitbucket.org/pygame/pygame
  - python -c "import pygame; print(pygame.__version__)"

install:
  - pip install -r dev-requirements.txt
  - pip install .

script:
  - py.test --cov=./xoinvader --cov-report=xml --strict -v

after_success:
  - codecov
